M48
; DRILL file {KiCad (6.0.4)} date Mon May  2 14:14:34 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-02T14:14:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.670
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X117.875Y-71.64
X172.275Y-108.6
T2
X124.65Y-78.74
X124.65Y-101.5
X165.5Y-78.74
X165.5Y-101.5
T0
M30
